nelmio_api_doc:
    documentation:
        info:
            title: Fan Folio
            description: This application is designed to log the releases of Franco-Belgian comics, comics, manga, and steelbook Blu-rays.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/v1
