version: "3"
networks:
  traefik_web:
    external: true
services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: simple-clean-architecture-php
    environment:
      APACHE_RUN_GROUP_ID: 1000
      APACHE_RUN_USER_ID: 1000
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      - traefik.http.routers.simple-clean-architecture.entrypoints=web
      - traefik.http.routers.simple-clean-architecture.rule=Host(`${APP_HOST}`)
  postgres:
    image: postgres:${DB_VERSION}
    container_name: simple-clean-architecture-postgres
    networks:
      - traefik_web
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    container_name: simple-clean-architecture-pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      - traefik.http.routers.pg-simple-clean-architecture.entrypoints=web
      - traefik.http.routers.pg-simple-clean-architecture.rule=Host(`${APP_PG_ADMIN}`)
    links:
      - "postgres:pgsql-server"

volumes:
  database_data:
