version: "3.8"
networks:
  traefik_web:
    external: true
services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: simple-clean-architecture-php
    environment:
      APACHE_RUN_GROUP_ID: 1000
      APACHE_RUN_USER_ID: 1000
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      - traefik.http.routers.simple-clean-architecture.entrypoints=web
      - traefik.http.routers.simple-clean-architecture.rule=Host(`${APP_HOST}`)
