#!/bin/sh
echo "###################   Configuring user mod and permission of www-data..."
set -e
usermod -u ${APACHE_RUN_USER_ID:-33} www-data
groupmod -g ${APACHE_RUN_GROUP_ID:-33} www-data

echo "###################   Configuring www-data permission on /var/www/..."
chown www-data:www-data /var/www/ -R

echo "###################   Start environnement configuration..."
echo "###################   You are in ${APP_ENV:-prod} environnement"

if [ "${APP_ENV:-prod}" = "dev" ] ; then
	echo "###################   Starting apache2 webserver"
elif [ "${APP_ENV:-prod}" = "prod" ]; then
	echo "Configuring symphony environment to prod"
	export SYMFONY_ENV=${APP_ENV}
	su www-data -s /bin/bash -c 'make build'
else
	echo "###################   Unknown env ${APP_ENV} !! Exiting..."
	exit 1
fi

exec "$@"