login_check:
    path: /v1/login-check

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

################################################### USER ###############################################################
user_create:
    path:     v1/users
    defaults: { _controller: 'App\Controller\UserController::create' }
    methods:  POST

user_list:
    path:     v1/users
    defaults: { _controller: 'App\Controller\UserController::list' }
    methods:  GET

user_read:
    path:     v1/users/{id}
    defaults: { _controller: 'App\Controller\UserController::read' }
    methods:  GET