services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

################################################# USE CASES ############################################################
    App\Event\EventSubscriber\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Serializer\FormErrorsSerializer:

    App\Event\EventListener\ExceptionListener:
        arguments:
            - '@jms_serializer'
            - '@App\Serializer\FormErrorsSerializer'
            - '@translator.default'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    App\Api\Model\ModelValidator:
        arguments:
            - '@form.factory'

################################################# USE CASES ############################################################
    App\UseCase\User\UserCreate:
        arguments:
            - '@app.repo.user'

    App\UseCase\User\UserList:
        arguments:
            - '@app.repo.user'

    App\UseCase\User\UserRead:
        arguments:
            - '@app.repo.user'

########################################## REPOSITORY ALIASES ##########################################################
    app.repo.user:
        public: true
        alias: 'App\Repository\UserRepository'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true

        app.repo.user:
            alias: 'App\Repository\Fake\UserRepository'